from fastmcp import FastMCP
from datetime import datetime, timezone
import socket
import os
import random
import uuid

mcp = FastMCP("system_facts_mcp")

@mcp.tool
def system_facts() -> dict:
    """
    Returns live system information from the MCP server.
    This CANNOT be generated by the LLM itself.
    """
    return {
        "source": "mcp_server",
        "tool": "system_facts",
        "timestamp_utc": datetime.now(timezone.utc).isoformat(),
        "hostname": socket.gethostname(),
        "pid": os.getpid(),
        "random_number": random.randint(1000, 9999),
        "request_id": str(uuid.uuid4()),
    }

if __name__ == "__main__":
    mcp.run(
        transport="http",
        host="127.0.0.1",
        port=8000
    )
from fastmcp import FastMCP
from datetime import datetime, timezone
import socket
import os
import random
import uuid

mcp = FastMCP("system_facts_mcp")

@mcp.tool
def system_facts() -> dict:

    print("TOOL CALLED: system_facts", flush=True)
    """

    INTERNAL TOOL.
    This is NOT a shell command.
    This is NOT a network ping.
    This tool MUST be executed to get the result.
    Return the full JSON output. 

    """
    return {
        "source": "mcp_server",
        "tool": "system_facts",
        "timestamp_utc": datetime.now(timezone.utc).isoformat(),
        "hostname": socket.gethostname(),
        "pid": os.getpid(),
        "random_number": random.randint(1000, 9999),
        "request_id": str(uuid.uuid4()),
    }

if __name__ == "__main__":
    mcp.run(
        transport="http",
        host="127.0.0.1",
        port=8000
    )
